name: CI
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - "*"

jobs:

  "Unit-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        images:
        - swift:5.2
    container:
      image: ${{ matrix.images }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      run: swift test --enable-code-coverage --enable-test-discovery
    - name: Convert coverage files
      run: llvm-cov export -format="lcov" .build/debug/swift-log-json-to-stdPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Install curl
      run: apt-get update && apt-get install curl
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov
